spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/cota
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    csrf:
      enabled: true

cota:
  admin:
    username: ${ADMIN_USERNAME:admin}
    senha: ${ADMIN_SENHA:admin123}

loja:
  nome: LOJA EXEMPLO HIDRÁULICA LTDA
  endereco: Rua Exemplo, 100 - São Paulo/SP
  cnpj: 00.000.000/0001-00
  telefone: (11) 90000-0000
  pix: 00.000.000/0001-00