spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/cota
    username: postgres
    password: postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: cota-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5051:80"
    depends_on:
      - postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true