CREATE TABLE usuario (
                         id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         username VARCHAR(255) NOT NULL UNIQUE,
                         senha    VARCHAR(255) NOT NULL,
                         setor    VARCHAR(20)  NOT NULL,
                         role     VARCHAR(20)  NOT NULL
);

CREATE TABLE orcamento (
                           id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           tipo             VARCHAR(20),
                           setor            VARCHAR(20)    NOT NULL,
                           empresa          VARCHAR(255)   NOT NULL,
                           cnpj             VARCHAR(14),
                           tipo_retirada    VARCHAR(20)    NOT NULL,
                           endereco_envio   VARCHAR(255),
                           forma_pagamento  VARCHAR(20)    NOT NULL,
                           dias_faturamento INTEGER,
                           frete            NUMERIC(12, 2),
                           observacao       VARCHAR(255),
                           status           VARCHAR(20)    NOT NULL,
                           data_criacao     TIMESTAMP(6)   NOT NULL
);

CREATE TABLE item_orcamento (
                                id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                produto        VARCHAR(255)   NOT NULL,
                                codigo         VARCHAR(255),
                                quantidade     INTEGER        NOT NULL,
                                preco_unitario NUMERIC(12, 2) NOT NULL,
                                orcamento_id   BIGINT         NOT NULL REFERENCES orcamento (id)
);

CREATE TABLE ordem_manutencao (
                                  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  cliente           VARCHAR(255)  NOT NULL,
                                  telefone          VARCHAR(255),
                                  produto           VARCHAR(30)   NOT NULL,
                                  codigo_produto    VARCHAR(255),
                                  problema_relatado VARCHAR(1000) NOT NULL,
                                  observacao        VARCHAR(1000),
                                  data_criacao      TIMESTAMP(6)  NOT NULL
);