ALTER TABLE ordem_manutencao RENAME COLUMN cliente TO empresa;
ALTER TABLE ordem_manutencao ADD COLUMN comprador VARCHAR(255);
ALTER TABLE ordem_manutencao ADD COLUMN email VARCHAR(255);

CREATE TABLE item_manutencao (
                                 id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 produto    VARCHAR(30)  NOT NULL,
                                 codigo     VARCHAR(255),
                                 quantidade INTEGER      NOT NULL,
                                 ordem_id   BIGINT       NOT NULL REFERENCES ordem_manutencao (id)
);

INSERT INTO item_manutencao (produto, codigo, quantidade, ordem_id)
SELECT produto, codigo_produto, 1, id
FROM ordem_manutencao;

ALTER TABLE ordem_manutencao DROP COLUMN produto;
ALTER TABLE ordem_manutencao DROP COLUMN codigo_produto;